### ISSUE TITLE
Missing `debuglog` method

### ISSUE THREAD

**Issue by barneycarroll** [caspervonb/node-rdbg#7]
```
/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:7
const debug = util.debuglog('rdbg');
                   ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:7:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/amok/lib/index.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by caspervonb** [comment]
This is from node's core, there's an implicit requirement on node ^v0.12. Lower versions won't have it available.

Not sure if I'm willing to downgrade, more likely to upgrade when io.js converges with node.

So basically this comes down to if there's anything actionable to do here, lets keep the discussion to https://github.com/caspervonb/amok/issues/102 :smile:

**Comment by barneycarroll** [comment]
Gotcha. I don't think there's anything wrong with making razor-toothed a requirements of the environment — it's not as if this is intended for use in production environments after all.
